# Generated by Django 5.2.14 on 2026-05-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MainPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=300)),
                ("description", models.TextField()),
                ("profile_image", models.URLField(blank=True, null=True)),
                ("resume_url", models.URLField(blank=True, null=True)),
                ("github_url", models.URLField(blank=True, null=True)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                ("about_title", models.CharField(default="About Me", max_length=200)),
                ("about_description", models.TextField(blank=True)),
                (
                    "skills",
                    models.TextField(
                        blank=True, help_text="Python, Django, DRF, PostgreSQL..."
                    ),
                ),
                ("years_experience", models.PositiveIntegerField(default=0)),
                ("total_projects", models.PositiveIntegerField(default=0)),
                ("happy_clients", models.PositiveIntegerField(default=0)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("page_title", models.CharField(blank=True, max_length=200)),
                ("meta_description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
